xsens_imu_node:
  ros__parameters:
    port: /dev/ttyUSB0
    hz: 30.0
    publish_magnetic: False
    
    publishers:
      imu_data: /imu/data
      magnetic_data: /imu/magnetic

    frames:
      imu_link: imu_link
      magnetic_imu_link: magnetic_imu_link